// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiHAdoFEEQICEbVT0hRIs6BGN0oZqb0KY',
    appId: '1:537435540327:web:db7a33a1389b76ecc33dc2',
    messagingSenderId: '537435540327',
    projectId: 'tutorat-e6f75',
    authDomain: 'tutorat-e6f75.firebaseapp.com',
    storageBucket: 'tutorat-e6f75.appspot.com',
    measurementId: 'G-E3NG0MNSNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgz1QyGxjSLyxxBzLX8Mc3qV3wsGFhbYE',
    appId: '1:537435540327:android:5637c52756c54374c33dc2',
    messagingSenderId: '537435540327',
    projectId: 'tutorat-e6f75',
    storageBucket: 'tutorat-e6f75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5LgmtzSU5qzqzS-FvFcpue2L7-lJsPBk',
    appId: '1:537435540327:ios:5725d50046fade46c33dc2',
    messagingSenderId: '537435540327',
    projectId: 'tutorat-e6f75',
    storageBucket: 'tutorat-e6f75.appspot.com',
    iosClientId:
        '537435540327-8mbkn6b7s766mitr09871tgiq0gp8tc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorat2022',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5LgmtzSU5qzqzS-FvFcpue2L7-lJsPBk',
    appId: '1:537435540327:ios:5725d50046fade46c33dc2',
    messagingSenderId: '537435540327',
    projectId: 'tutorat-e6f75',
    storageBucket: 'tutorat-e6f75.appspot.com',
    iosClientId:
        '537435540327-8mbkn6b7s766mitr09871tgiq0gp8tc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorat2022',
  );
}
